permalink: /:categories/:year/:month/:title

highlighter: pygments
markdown: rdiscount
rdiscount:
  toc_token: "[TOC]"
  extensions:
    - autolink
    - footnotes
    - smart
    - generate_toc

manageremail: quantumjulia@gmail.com
