permalink: /:categories/:year/:month/:title

highlighter: pygments

markdown: rdiscount
rdiscount:
  toc_token: "[TOC]"
  extensions:
    - smart
    - generate_toc

chapters:
  - Introduction: introduction
  - Getting Started: getting-started


